export const HANDLE_CHANGE_QUANTITY_INTO_CART = 'HANDLE_CHANGE_QUANTITY_INTO_CART'
export const DELETE_CART_ELEMENT = 'DELETE_CART_ELEMENT'
export const PUT_CART_ITEM = 'PUT_CART_ITEM'
//
export const SAGA_CHANGE_CART = 'SAGA_CHANGE_CART'
//
export const ACTION_CHANGE_OPEN_CART = 'ACTION_CHANGE_OPEN_CART'
export const CHANGE_OPEN_CART = 'CHANGE_OPEN_CART'
//
export const ACTION_SELECT_CART_ITEM = 'CALL_SELECT_CART_ITEM'
export const SELECT_CART_ITEM = 'SELECT_CART_ITEM'