export type CALL_CART_STATE = "CALL_CART_STATE"

type CART_IS_OPEN_SAVE = "CART_IS_OPEN_SAVE"
type CART_ADD_ITEM_SAVE = "CART_ADD_ITEM_SAVE"
type CART_DELETE_ITEM_SAVE = "CART_DELETE_ITEM_SAVE"
type CART_CHANGE_QUANTITY_SAVE = "CART_CHANGE_QUANTITY_SAVE"
type CART_SELECT_ITEM_SAVE = "CART_SELECT_ITEM_SAVE"

type CartActionsTypes = CART_IS_OPEN_SAVE | CART_ADD_ITEM_SAVE | CART_DELETE_ITEM_SAVE | CART_CHANGE_QUANTITY_SAVE | CART_SELECT_ITEM_SAVE

export default CartActionsTypes;