'use client'

import './globals.css'
import '../../public/styles/index.scss'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import {ThemeProvider, createTheme} from '@mui/material'

import {Provider} from 'react-redux'
import store from '@/redux/store'
import { ReactNode } from 'react'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const theme = createTheme({
  palette: {
    primary: {main: '#000'},
    secondary: {main: '#000'},
    success: {main: '#10b981'}
  }
})

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({children}: {children: ReactNode}) {

  return (
    <html lang="en">
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <body className={roboto.className}>
            {children}
          </body>
        </ThemeProvider>
      </Provider>
    </html>
  )
}
