export const GET_PRODUCT_ID = 'GET_PRODUCT_ID'
export const SET_PRODUCT_ID = 'SET_PRODUCT_ID'

export const SAVE_DATA_FROM_DB = 'SAVE_DATA_FROM_DB'
export const SAVE_DATA_FROM_DB_REDUCER = 'SAVE_DATA_FROM_DB_REDUCER'
export const SAVE_DATA_FROM_DB_ACTION = 'SAVE_DATA_FROM_DB_ACTION'